version: "3"

services:
  origin:
    # image: nginx:1.21.3-alpine
    image: fholzer/nginx-brotli
    volumes:
      - ./www:/www
      # - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./brotli.conf:/etc/nginx/conf.d/brotli.conf
      # - /home/lzy/pcap/origin/nginx:/pcap
    ports:
      - "80:80"